Only use postgresTester on empty db configuration RMB-826
folio-org/raml-module-builder pull request #907
Opened 2021-04-16 19:00 UTC by adamdickmeiss

2021-04-17 23:05 UTC, hjiebsco approved these changes

2021-04-17 23:05 UTC, hjiebsco commented on domain-models-runtime/src/main/java/org/folio/rest/persist/PostgresClient.java
> +    if (isEmbedded() && postgreSQLClientConfig.containsKey("testing")) {
Technically it should check for `true` and there is no unit test to cover the new condition.

2021-04-19 10:38 UTC, julianladisch requested changes
I cannot review this because there is no use case on RMB-826 that shows why this is needed.
This looks like a breaking change, but documentation in README is missing.

2021-04-19 13:12 UTC, adamdickmeiss commented
> I cannot review this because there is no use case on RMB-826 that shows why this is needed.
> This looks like a breaking change, but documentation in README is missing.

I have added some material there now.. There's not a good place to put it in current manual.. But I agree that *something* somewhere should be added. .. TestContainers only mentioned once (in a sentence that really doesn't mean much to me)

2021-04-19 20:27 UTC, julianladisch commented on doc/upgrading.md
> +*not used for testing. This allows testing to be performed on local
```suggestion
*not* used for testing. This allows testing to be performed on local
```

2021-04-19 20:27 UTC, julianladisch approved these changes
Looks good, thanks!

2021-04-21 09:02 UTC, adamdickmeiss commented on doc/upgrading.md
> +*not used for testing. This allows testing to be performed on local
right

2021-04-21 09:02 UTC, merged